server:
  port: 8080

spring:
  application:
    name: parking-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:parking_spaces}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${CLERK_JWKS_URI}

esewa:
  product-code: ${ESEWA_PRODUCT_CODE:EPAYTEST}
  secret-key: ${ESEWA_SECRET_KEY:8gBm/:&EnhH.1/q}
  esewa-url: ${ESEWA_URL:https://rc-epay.esewa.com.np/api/epay/main/v2/form}
  status-url: ${ESEWA_STATUS_URL:https://rc-epay.esewa.com.np/api/epay/transaction/status/}
  success-url: ${ESEWA_SUCCESS_URL:http://localhost:3000/search}
  failure-url: ${ESEWA_FAILURE_URL:http://localhost:3000/search}

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

gemini:
  api:
    key: ${GEMINI_API_KEY:}
